name: GivetotheMaker
favicon: null
layout_spectrum: 0.73279
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffeff'
    - '#1f1f1f'
    - '#636262'
    - '#6f6f6f'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
