name: GivetotheMaker
favicon: null
layout_spectrum: 0.4933
typography_spectrum: 0.74155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dffdff'
    - '#3c7d7e'
    - '#6fd2cf'
    - '#00333c'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
