name: GivetotheMaker
favicon: null
layout_spectrum: 0.51822
typography_spectrum: 0.74155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#14373d'
    - '#25616b'
    - '#44aebe'
    - '#358e9c'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
