name: GivetotheMaker
favicon: null
layout_spectrum: 0.51759
typography_spectrum: 0.48649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 1
  lightness: 0.24665889493189752
  saturation: 0.45727235078811646
  rhythmicContrast: 0.468034409917891
purpose: []
