name: GivetotheMaker
favicon: null
layout_spectrum: 0.4933
typography_spectrum: 0.74155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8e8e8'
    - '#aaaaaa'
    - '#232323'
    - '#7e7e7e'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
