name: GivetotheMaker
favicon: null
layout_spectrum: 0.17814
typography_spectrum: 0.74155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8e8e8'
    - '#a5a5a5'
    - '#525252'
    - '#7d7d7d'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
