layout_spectrum: 0.3431703
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.5
  rhythmicContrast: 0
  brandColors:
    - '#000000'
  lightness: 0
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: GivetotheMaker
